### ISSUE TITLE
Change country

### ISSUE THREAD

**Issue by Phil099** [Path-Check/dcc-sdk.js#10]
Hello,
I want to use this generator : https://github.pathcheck.org/eu.dgc.html 
I think it is made with your code.
It contains a pass for Nederlands. How can I change this NL pass to a pass for FRANCE ?
I tried to change NL to FR but I think I have also to change "Issuer" and "Cert ID".
Thank you

**Comment by vitorpamplona** [comment]
Hi Phil, 

The generator is just a demo for the library. In order to generate a code as France, you will have to use the French services. They are the only ones with the private key required to generate the QR with the appropriate issuer and Cert ID. 

Best,
