### ISSUE TITLE
Problems importing the library from a ESM module

### ISSUE THREAD

**Issue by oyooyo** [Path-Check/dcc-sdk.js#2]
Hello,

I just wanted to create a minimal script for trying out this library and came across two issues that I want to report.

I created a new directory and installed the library as mentioned in the README via
```
npm install @pathcheck/dcc-sdk --save
```

As I get it, the library is already implemented as ESM, and the file `index.js` basically just converts the whole thing to CommonJS. But I wasn't sure how to properly import the library, ideally without converting the ESM module to CommonJS first and then back to ESM again, by directly accessing main.js instead of index.js.

So maybe you could mention how to properly import the library in the README file, both via ESM and CommonJS?

Anyway, since I wasn't sure how to import the library via ESM, I started by simply creating a minimal `test.mjs` file just to see what's being exported and how to import it:
```javascript
import * as dcc_sdk1 from '@pathcheck/dcc-sdk';

console.log('a1', dcc_sdk1);

import dcc_sdk2 from '@pathcheck/dcc-sdk';

console.log('a2', dcc_sdk2);

```
I ran the script via `node test.mjs` (Node version v14.17.0, AFAIK the latest LTS release), but for some reason, the output suggested that nothing was being imported at all:
```
a1 [Module: null prototype] { default: {} }
a2 {}
```

Strangely, when I made a tiny modification to the `index.js` file of dcc-sdk, by simply replacing the line
```
module.exports = require('./main.js');
```

with 

```
const main = require('./main.js');
module.exports = main;
```

the output of my little test script suggested that everything was now imported just fine (even though I don't understand why it even makes any difference):

```
a1 [Module: null prototype] {
  default: {
    sign: [AsyncFunction: sign],
    verify: [AsyncFunction: verify],
    pack: [AsyncFunction: pack],
    unpack: [AsyncFunction: unpack],
    signAndPack: [AsyncFunction: signAndPack],
    unpackAndVerify: [AsyncFunction: unpackAndVerify],
    signAndPack32: [AsyncFunction: signAndPack32],
    signAndPack45: [AsyncFunction: signAndPack45],
    makeCWT: [AsyncFunction: makeCWT],
    parseCWT: [AsyncFunction: parseCWT],
    debug: [AsyncFunction: debug],
    encode: [Function: encode],
    decode: [Function: decode],
    decodeToUtf8String: [Function: decodeToUtf8String]
  }
}
a2 {
  sign: [AsyncFunction: sign],
  verify: [AsyncFunction: verify],
  pack: [AsyncFunction: pack],
  unpack: [AsyncFunction: unpack],
  signAndPack: [AsyncFunction: signAndPack],
  unpackAndVerify: [AsyncFunction: unpackAndVerify],
  signAndPack32: [AsyncFunction: signAndPack32],
  signAndPack45: [AsyncFunction: signAndPack45],
  makeCWT: [AsyncFunction: makeCWT],
  parseCWT: [AsyncFunction: parseCWT],
  debug: [AsyncFunction: debug],
  encode: [Function: encode],
  decode: [Function: decode],
  decodeToUtf8String: [Function: decodeToUtf8String]
}
```

**Comment by vitorpamplona** [comment]
Very interesting. I am facing a similar issue with React-Native. 

Ideally, if you are using ES6 you should be able to import directly from main.js. 

I know the current code works well for other node.js apps and webpack can create CommonJS scripts just fine. But I have not tested other environments.  

I really don't know why this one below is not working for you. I did the same in a new node module and it did work 

```
import * as dcc_sdk1 from '@pathcheck/dcc-sdk';

console.log('a1', dcc_sdk1);
```

I will investigate more.

**Comment by oyooyo** [comment]
> I really don't know why this one below is not working for you. I did the same in a new node module and it did work
> 
> ```
> import * as dcc_sdk1 from '@pathcheck/dcc-sdk';
> 
> console.log('a1', dcc_sdk1);
> ```

Strange. I just tried again just to rule out that maybe I had done some stupid error. I also installed the latest versions of node (v16.3.0) and npm to rule out that this makes any difference, then cleared the whole directory, installed dcc-sdk again, created a file test.mjs, copy and pasted above code into it and ran it via `node test.mjs`. No difference though:
```
a1 [Module: null prototype] { default: {} }
```

Btw, when I created a test-webapp via create-react-app, importing dcc-sdk worked perfectly fine for me as well. I guess that's because in this case the code is being bundled first, so it's a different situation.

And it also works fine for me when the test script is classical CommonJS:
> ```
> const dcc_sdk1 = require('@pathcheck/dcc-sdk');
> 
> console.log('a1', dcc_sdk1);
> ```

The only situation when I ran into this problem was when I used ESM imports without any bundler etc.

> Ideally, if you are using ES6 you should be able to import directly from main.js.

I've looked a little deeper into this and found a few resources that seemed to be relevant, as I assume the problem is related to providing a hybrid ESM/CommonJS package:
[Dual CommonJS/ES module packages](https://nodejs.org/api/packages.html#packages_dual_commonjs_es_module_packages)
[Conditional exports](https://nodejs.org/api/packages.html#packages_conditional_exports)
[How to Create a Hybrid NPM Module for ESM and CommonJS](https://www.sensedeep.com/blog/posts/2021/how-to-create-single-source-npm-module.html)

I tried a few things mentioned there, like adding an "exports" section to package.json, setting `"type":"module"`, changing some file extensions etc., but nothing really worked. But that just caused new problems and it always only worked either via CommonJS or via ESM.

What did work however was the strange "solution" I mentioned in the first posting, of simply replacing `module.exports = require('./main.js');` with
```
const main = require('./main.js');
module.exports = main;
```
It's completely beyond me why this additional assignment makes any difference, but with this little workaround the code ran fine with either using CommonJS require() or ESM import.

**Comment by oyooyo** [comment]
I just tried again with latest version 0.0.11 and everything worked fine, both when importing as CommonJS and as ESM.
Since I do not understand why this weird workaround works, I am not 100% sure that the issue is completely solved - but since it works for me now, I'm closing the issue.

Thanks for your support.
