### ISSUE TITLE
KeyID not found:  XkVWZqUeeFc

### ISSUE THREAD

**Issue by mheers** [Path-Check/dcc-sdk.js#4]
Hello,

first of all thank you very much for developing this library. I could already successfully debug a vaccination certificate.

I tested a German certificate but it can not be verified due to the error message `KeyID not found:  XkVWZqUeeFc`.

I'm not sure if the public keys are out of the scope of this project but I saw some in the `resolver.js` so maybe there is 'just' ca key missing.

**Comment by vitorpamplona** [comment]
DCC's key management is purely manual at this time since there are not public gateways to download keys from member states (which is a shame IMHO) :( 

I hope to get access to this key soon and add it to the lib.

**Comment by pc-coholic** [comment]
Since I was looking for exactly the same key, too: Here you go: https://de.dscg.ubirch.com/trustList/DSC/

I cannot say if that is Ubirch's version of the EU-DGC-Gateway - but since it's servicing the german COVPass-Verifier apps *and* includes non-German keys, I would assume that this might be a viable source for the future.

**Comment by vitorpamplona** [comment]
Thanks @pc-coholic!! I will add.

**Comment by vitorpamplona** [comment]
Release 0.0.12 is out on npmjs. :)

**Comment by mheers** [comment]
Thank you all for finding and adding the key. I can now see the key in the `resolver.js` but I'm still unable to verify due to the following error:

```
> KeyID not found:  XkVWZqUeeFc
Error: pem: invalid base64 body
    at parse (./node_modules/@fidm/asn1/build/pem.js:168:15)
    at Function.parse (./node_modules/@fidm/asn1/build/pem.js:45:22)
    at Function.fromPEMs (./node_modules/@fidm/x509/build/x509.js:241:33)
    at Function.fromPEM (./node_modules/@fidm/x509/build/x509.js:264:28)
    at getParamsFromPEM (./node_modules/@pathcheck/dcc-sdk/lib/dcc.js:33:28)
    at verifyAndReturnPayload (./node_modules/@pathcheck/dcc-sdk/lib/dcc.js:222:19)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async unpackAndVerify (./node_modules/@pathcheck/dcc-sdk/lib/dcc.js:324:12)
```

**Comment by vitorpamplona** [comment]
hum... there seems to be an issue on the KeyID itself. On the trustList, this key is registered as `XkVWZqUeeFc=` but it looks like your QR has it without the `=` sign: `XkVWZqUeeFc`. In theory, they are supposed to be different keys. 

Are you generating this cert or did you get it from somebody else? 

You can paste it here to see how the KeyID is written in the payload: https://github.pathcheck.org/debug.html

**Comment by vitorpamplona** [comment]
Or maybe, the decode of the keyID byte array in our lib is defaulting to Base64URL, which I believe was the initial intent.

**Comment by mheers** [comment]
> hum... there seems to be an issue on the KeyID itself. On the trustList, this key is registered as `XkVWZqUeeFc=` but it looks like your QR has it without the `=` sign: `XkVWZqUeeFc`. In theory, they are supposed to be different keys.
> 
> Are you generating this cert or did you get it from somebody else?
> 
> You can paste it here to see how the KeyID is written in the payload: https://github.pathcheck.org/debug.html

This is an officially created code.

The debug json starts with
```json
{
  "tag": 18,
  "value": [
    { "Map": [ [ 1, -7 ] ] },
    { "Map": [ [ 4, "XkVWZqUeeFc" ] ] },
    {
      "Map": [
        [ 1, "DE" ],
        [ 4, 1655193786 ],
        [ 6, 1623657786 ],
        [
          -260,
          {
            "Map": [
              [
                1,
                {
                  "v": [
```

**Comment by vitorpamplona** [comment]
Awesome! Thanks, this means that I should change it to test both since the underlying byte array is the same.

**Comment by vitorpamplona** [comment]
Version 0.0.13 is up and should fix this issue. Let me know if it doesn't.

**Comment by mheers** [comment]
Thank you very much! It now works perfectly!

For those who use it with the `@pathcheck/universal-verifier-sdk` can override the `@pathcheck/dcc-sdk` in the `package.json` like

```json
{
    "dependencies": {
        "@pathcheck/universal-verifier-sdk": "^0.0.2"
    },
    "resolutions": {
        "@pathcheck/dcc-sdk": "^0.0.13"
    }
}
```
