### ISSUE TITLE
Setting up CSCA, DCS and Key IDs

### ISSUE THREAD

**Issue by PietroGranati** [Path-Check/dcc-sdk.js#8]
Hi, first of all thank you for this lib, I was trying to test it but I'm stuck with the command ./gen-csca-dsc.sh
The terminal change title to "openssl" but stay still, it generates only the "csca.key"
Any suggestion?

**Comment by vitorpamplona** [comment]
HI Pietro, 

Did you try to run the script line by line on the shell? You just need to replace the `OPENSSL` to `openssl` or a similar command you are using on your system.

**Comment by PietroGranati** [comment]
Ok just tryed, the command:
`openssl req -x509 \
	-subj '/CN=National CSCA of Friesland/C=FR/' \
	-key csca.key \
	-out csca.pem -nodes \
	-days 3650`
	
Stay there and don't gave signal or errors

**Comment by vitorpamplona** [comment]
Nice, so, it's something with OpenSSL. 

can you try without `\` just to make sure? 

```
openssl req -x509 -subj '/CN=National CSCA of Friesland/C=FR/' -key csca.key -out csca.pem -nodes -days 3650
```

Which OS are you using? And which openssl version? (`openssl -version`)

**Comment by PietroGranati** [comment]
It seems to stay stuck.
I'm using mac os.
Result:
`openssl version
LibreSSL 2.8.3`

**Comment by vitorpamplona** [comment]
oh interesting.. I have not tested LibreSSL yet, only OpenSSL itself. 

My hunch is that they added another requirement for the command line of LibreSSL that is not compatible with OpenSSL. I can do some more research on it.

**Comment by PietroGranati** [comment]
Ok, maybe I can too, in the meantime I'll try to find a pc with OpenSSL and retry :)

**OFF-TOPIC**
In the meantime I was also testing your other module, I don't know if I'm doing it right, I'm trying to check a qrcode string from green card
https://github.com/Path-Check/universal-verifier-sdk/issues/1

**Comment by PietroGranati** [comment]
Ok, I fixed the problem on Mac OS.
macOS provides by default LibreSSL, so we need to install openssl with brew.
Follow this guide: https://medium.com/@timmykko/using-openssl-library-with-macos-sierra-7807cfd47892

After following the guide make sure to run the suggestions:
```
For compilers to find openssl@1.1 you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"
```
And re-run the script!
