### ISSUE TITLE
Problem with the Digital COVID Certificate

### ISSUE THREAD

**Issue by Rbonaconsa** [Path-Check/dcc-sdk.js#9]
Dear Vitorpamplona

I Have used your code, https://github.pathcheck.org/eu.dgc.html, here and used the CH1 generated QR Code. Everything works only if I check it with the official Corona app an failure occurs. COVID Certificate has no valid singature.
I have used the COVID CERTIFICATE app for Samsung to read in the CH1 generated QR Code, it exchanged it to an othere QR Code where all the datas are correct. But the problem is if I scan now this code with the COVID CERTIFICATE 
CHECK app it shows Certificate has no valid signature. 
All the APPS are from Switzerland Government. 
If anyone can helpf me fixing it I would very appreciate.

I do not have the programming background available and no progrmmer tool. 

Thanks a lot and help is very appreciated

**Comment by vitorpamplona** [comment]
Hi Rico, the EU law only allows countries to create new credentials for these official apps. Unless you use our library with a key approved by an EU member state, no app will verify the QR code.

**Comment by Rbonaconsa** [comment]
Hi Vitor understood. Thanks for the reply

Appreciated Rico
